config/routes.rb
Quizapp::Application.routes.draw do
  resources :questions

  get "quiz/index"

  post "quiz/start"

  get "quiz/question"

  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"

  post "choices/create"

  post "choices/destroy"

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :choices

  def answer
	 uncorrect
	 choices.select {|c| c.correct}[0]
  end

  def uncorrect
	 choices.each {|c| c.correct = false}
  end

  def answer= choice
	 if !answer.nil?
		answer.correct = false
	 end

	 if choices.include? choice
		choice.correct = true
	 else
		choices << choice
		choice.correct = true
	 end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
   GET /questions
   GET /questions.xml
  def index
    @questions = Question.all
    @questions.sort! {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html # index.html.erb
    end
  end

 GET /questions/1
  GET /questions/1.xml

  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      
    end
  end

  GET /questions/new
  GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      
    end
  end
  
  

  

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end
  
  def start
	 total = params[:number].to_i
	 all = Question.find(:all).map {|x| x.id}
	 session[:questions] = all.sort_by{rand}[0..(total-1)]
	 
	 session[:total]   = total
	 session[:current] = 0
	 session[:correct] = 0
	 
	 redirect_to :action => "question"
  end

  def question
	 @current = session[:current]
	 @total   = session[:total]
	 
	 if @current >= @total
		redirect_to :action => "end"
		return
	 end
	 
	 @question = Question.find(session[:questions][@current])
	 @choices = @question.choices.sort_by{rand}
	 
	 session[:question] = @question
	 session[:choices] = @choices
  end

  def answer
	 @current = session[:current]
	 @total   = session[:total]
	 
	 choiceid = params[:choice]
	 
	 @question = session[:question]
	 @choices  = session[:choices]
	 
	 @choice = choiceid ? Choice.find(choiceid) : nil
	 if @choice and @choice.correct
		@correct = true
		session[:correct] += 1
	 else
		@correct = false
	 end
	 
	 session[:current] += 1
  end

  def end
	 @correct = session[:correct]
	 @total   = session[:total]
	 
	 @score = @correct * 100 / @total
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>


<div id="main">
  <%= yield %>

 
  <div id="footer">
	 

</body>
</html>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path %></p>

<table border="1">
  <tr>
    <th>Text</th>
    <th>Choices</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
          <li>
            <%= choice.text %>
            <% if choice.correct %> (Correct) <% end %>
          </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Show', question %>
    </td>
  </tr>
<% end %>
</table>



<% content_for(:title) do %>
  All Questions
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @question.text %>
</p>

<h4>Choices</h4>
<ul>
  <% @question.choices.each do |choice| %>
	 <li>
		<%= choice.text %>
		<% if choice.correct %> (Correct) <% end %>

	 </li>
  <% end %>
</ul>

<h5>New Choice</h5>
<%= form_tag({:controller => "choices", :action => "create"}) do %>
  <%= hidden_field_tag :question, @question.id %>

  <%= label_tag :text, "Text" %><br />
  <%= text_field_tag :text %>
  <br />
  <%= check_box_tag :correct %>
  <%= label_tag :correct, "Correct" %>
  <br />
  
<% end %>


<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Question Details
<% end %>

app/views/quiz/answer.html.erb
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<div id="feedback-choices">
  <% @choices.each do |choice| %>
	 <% if choice.correct %>
		<p class="correct feedback-choice">
	 <% elsif choice == @choice %>
		<p class="incorrect feedback-choice">
	 <% else %>
		<p class="feedback-choice">
	 <% end %>
		<%= choice.text %>
	 </p>
  <% end %>
</div>

<p class="feedback">
  <% if @correct %>
	 Correct!!! Your So Smart & Awesome!!!
  <% else %>
	 Incorrect :( Don't Worry Be Happy!
  <% end %>
</p>

<%= form_tag({:controller => "quiz", :action => "question"}) do %>
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

<% content_for(:title) do %>
  Question <%= @current + 1 %> of <%= @total %>
<% end %>

app/views/quiz/end.html.erb
<h1>Results</h1>

<p id="question">You got <%= @correct %> out of <%= @total %> answers.</p>

<p id="score"><%= @score %>%</p>

<%=form_tag({:controller => "quiz", :action => "index"}, :method => "get") do %>
  <div class="center">
	 <%=submit_tag("Go Again!",:class => "Submit") %>
  </div>
<% end %>

<% content_for(:title) do %>
  Results
<% end %>

app/views/quiz/index.html.erb
<body background="hwwalk.gif">
<h1>Start Quiz</h1>
<%= form_tag({:controller => "quiz",
				  :action => "start"}) do %>
  <p><%= label_tag(:number, "How many questions do you want in the quiz?", :id => "question") %></p>
  <p class="center"><%= select_tag(:number, options_for_select((1..10).map {|x| [x, x]}), :id => "count") %> <br /></p>

  <div class="center">
	 <%= submit_tag "Start!", :class => "submit"%>
  </div>
<% end %>

<% content_for(:title) do %>
  Start Quiz
<% end %>

app/views/quiz/question.html.erb
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({:controller => "quiz", :action => "answer"}) do %>
  <% @choices.each do |choice| %>
	 <p class="choice">
		<%= radio_button_tag(:choice, choice.id) %>
		<%= label_tag("choice_".concat(choice.id.to_s).to_sym, choice.text) %>
	 </p>
  <% end %>

  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

<% content_for(:title) do %>
  Question <%= @current + 1 %> of <%= @total %>
<% end %>

app/views/quiz/start.html.erb
<!-- This file intentionally left empty -->